### ISSUE TITLE
Using Curl to talk to marathon instead of http not working

### ISSUE THREAD

**Issue by svennela** [mhausenblas/m-shop#2]
Hi,

I am using curl commands below 3 are resulting in the same error. Please help..
{"message":"Invalid JSON: JsResultException(errors:List((/id,List())))"}

curl -v -H "Content-Type: application/json" -X POST -d  @mesos-dns/system.json http://10.10.27.223:8080/v2/apps

 curl -v -H "Content-Type: application/json" -X POST --data-binary  @mesos-dns/system.json http://10.10.27.223:8080/v2/apps

 curl -v -H "Content-Type: application/json" -X POST --data  @mesos-dns/system.json http://10.10.27.223:8080/v2/apps

{"message":"Invalid JSON: JsResultException(errors:List((/id,List())))"}

**Comment by svennela** [comment]
Do you have documentation how to run with curl command??

**Comment by roynasser** [comment]
+1... I cant figure out where to get "http"... not i brew or in google lol

EDIT: to use CURL do:

curl -X PUT --data @mesos-dns/system.json http://10.141.141.10:8080/v2/groups -H "Content-Type: application/json"
curl -X POST --data @m-shop.json http://10.141.141.10:8080/v2/groups  -H "Content-Type: application/json"

**Comment by mhausenblas** [comment]
The `http` command is a CLI HTTP tool, written in Python and available via http://httpie.org
