### ISSUE TITLE
ZK watcher failed: timed out waiting for initial ZK detection, exiting

### ISSUE THREAD

**Issue by du2016** [mhausenblas/m-shop#3]
when i run mesos-dns as this:./mesos-dns -config config.js,a few minutes later it exit and say :ERROR: 2016/01/28 14:42:32 main.go:65: ZK watcher failed: timed out waiting for initial ZK detection, exiting

my config.json is:
{
  "zk": "zk://172.16.1.60:2181,172.16.1.61:2181,172.16.1.62:2181/mesos",
  "masters": ["172.16.1.60:5050","172.16.1.61:5050","172.16.1.62:5050"],
  "refreshSeconds": 60,
  "ttl": 60,
  "domain": "mesos",
  "port": 53,
  "resolvers": ["20.20.20.20"],
  "timeout": 5,
  "email": "root.mesos-dns.mesos"
}

my mesos-master has three mechine:"172.16.1.60:5050","172.16.1.61:5050","172.16.1.62:5050"  i don't know where i config is wrong,who can telll me why?

**Comment by mhausenblas** [comment]
Still an issue? If not, I'm closing this.
