### ISSUE TITLE
Not able to add to cart

### ISSUE THREAD

**Issue by ZeroGraviti** [mhausenblas/m-shop#4]
I am getting a 404 for the "add to cart" functionality. I checked everything else works. I am using playa-mesos customized to run on 192.168.xxx.yyy. The nginx 'frontend-static' app as launched through marathon is running on port 31000 and accessed using Firefox.
Here are the HTTP request and response headers for the "Add to cart" function taken from the NODE_DEBUG=request env setting :-
**_Request headers_**

```
GET /%5Bobject%20XMLDocument%5D/GET/f61496e5-b1b5-6a80-6d28-393b30b46e78 HTTP/1.1
Host: 192.168.56.106:31000
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
X-Requested-With: XMLHttpRequest
Referer: http://192.168.56.106:31000/
Connection: keep-alive
```

**_Response headers_**

```
HTTP/1.1 404 Not Found
Server: nginx/1.9.1
Date: Fri, 19 Feb 2016 13:34:23 GMT
Content-Type: text/html
Content-Length: 168
Connection: keep-alive
```

Can you help me fix this to get it to work ?

**Comment by mhausenblas** [comment]
Hi @ZeroGraviti — sorry for the delay, I have no idea why I don't get these notifications. Anyways, the request path looks strange. There shouldn't be a `/%5Bobject%20XMLDocument%5D/` (see also the respective [code](https://github.com/mhausenblas/m-shop/blob/master/frontend-static/content/m-shop.js#L27)). Two quick ideas: have you got CORS enabled? And also: which browser are you using?

**Comment by ZeroGraviti** [comment]
This trace was generated from UI interaction on Firefox v44.0.2 web browser. I can share results while testing with other browsers too. I had set env var NODE_DEBUG=request to try to understand whats going on in the server side nodejs app and trace results. This is what I have added to the issue above. I have tested the webdis app and the mesos-dns individually (in isolation) and they are working fine. I dont know how to test the sedi app since it is a non-dockerized app which we are deploying into mesos using marathon.
On a small sidenote, isn't it a bit strange why you have modeled this as a GET http request ?
Please let me know your thoughts.

**Comment by mhausenblas** [comment]
OK, thanks for this info. I still don't know if you've got CORS enabled (I used a Chrome plugin to allow access for this app, otherwise the front-end can't talk to webdis). Not sure what you mean how to test sedi, since it's part of my Mesos-DNS setup—or did you not launch [system.json](https://github.com/mhausenblas/m-shop/blob/master/mesos-dns/system.json) via Marathon?

Re the sidenote: because that's the [API that Webdis exposes](https://github.com/nicolasff/webdis#about) ;)

**Comment by ZeroGraviti** [comment]
I launched both the json files to create the respective apps in marathon. I believe CORS is enabled in Firefox for sometime now (by default) but I will double check. I could be wrong but I can test this with popular browsers like Chrome etc.. If you can share the exact Chrome version with me it will help. I will try to use vanilla versions of the browsers ( I usually add plugins like ABP and other stuff to block annoying things :) ) and let you know. Another way to triage this is if you can **_disable _**CORS and share your results with me. We can then compare. Either way, let me know how you want to do this.

SEDI gets deployed as a separate app in marathon, that's what I meant. However, there is no docker image which is pulled from the docker hub.
On the sidenote, I understand. However there is _more than one_ GET in that request line (verb plus path ???)

**Comment by ZeroGraviti** [comment]
Tested with CORS enabled in Chrome. Works perfectly. This bug can be closed.

**Comment by mhausenblas** [comment]
Perfect, thanks!
